# Generated by Django 4.2.2 on 2023-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='bio',
            field=models.CharField(default='Your Default Bio Value', max_length=50),
        ),
    ]
