# Generated by Django 4.2.2 on 2023-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mycustomuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='bio',
            field=models.CharField(default='Adventurous explorer of knowledge, always eager to learn and grow. 📚🚀', max_length=50),
        ),
    ]
