# Generated by Django 4.2.2 on 2023-07-19 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mycustomuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='bio',
            field=models.CharField(default='Adventurous explorer of knowledge, always eager to learn and grow. 📚🚀', max_length=150),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.', regex='^[\\w\\s.@+-]+$')]),
        ),
    ]
