# Generated by Django 4.2.2 on 2023-07-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_mycustomuser_bio_alter_mycustomuser_username'),
    ]

    operations = [
    ]
