# Generated by Django 4.2.2 on 2023-07-31 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230731_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
