# Generated by Django 4.2.2 on 2023-07-31 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
