# Generated by Django 4.2.2 on 2023-08-06 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_todo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='roll',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username or roll already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.', regex='^[\\w\\s.@+-]+$')]),
        ),
    ]
