# Generated by Django 4.2.5 on 2023-10-17 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_mycustomuser_roll_alter_mycustomuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
        migrations.AddField(
            model_name='contacts',
            name='roll',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='contacts',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
