# Generated by Django 4.2.5 on 2023-10-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_contacts_name_contacts_roll_contacts_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(max_length=2)),
                ('image', models.ImageField(upload_to='static\\image')),
            ],
        ),
    ]
