# Generated by Django 4.2.5 on 2023-10-19 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notes',
            name='pg_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notes',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='notes',
            name='chapter_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(default='', upload_to='static/image'),
        ),
    ]
