# Generated by Django 4.2.5 on 2023-10-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notes_author_notes_desc_notes_pg_no_notes_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notes',
        ),
    ]
