# Generated by Django 4.2.5 on 2023-10-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
