# Generated by Django 4.2.5 on 2023-10-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='chapter_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(upload_to='static/image/user_media'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='page',
            field=models.PositiveIntegerField(),
        ),
    ]
