# Generated by Django 4.2.5 on 2023-10-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_notes_chapter_no_alter_notes_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
