# Generated by Django 4.2.5 on 2023-10-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
