# Generated by Django 4.2.5 on 2023-10-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_notes_chapter_no_alter_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.CharField(default='', max_length=15),
        ),
    ]
