# Generated by Django 4.2.5 on 2023-10-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_notes_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
