# Generated by Django 4.2.5 on 2023-10-22 14:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/user_media')),
                ('subject', models.CharField(default='', max_length=15)),
                ('chapter_no', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=32, message='Chapter number must be between 1 and 32')])),
                ('page', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
