# Generated by Django 4.2.5 on 2023-10-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='image',
        ),
        migrations.AddField(
            model_name='notes',
            name='document',
            field=models.FileField(default='', upload_to='static/image/user_media'),
        ),
    ]
