# Generated by Django 4.2.5 on 2023-10-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_notes_image_notes_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='document',
            field=models.FileField(default='', upload_to='static/image/media/<django.db.models.fields.CharField>'),
        ),
    ]
