# Generated by Django 4.2.5 on 2023-10-23 12:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_notes_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='document',
            field=models.FileField(default='', upload_to=app.models.get_upload_path),
        ),
    ]
