# Generated by Django 4.2.5 on 2023-10-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_notes_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='page',
            field=models.CharField(max_length=15),
        ),
    ]
