# Generated by Django 4.2.5 on 2023-10-23 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_notes_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 17, 9, 50, 963628, tzinfo=datetime.timezone.utc)),
        ),
    ]
