# Generated by Django 4.2.5 on 2023-10-23 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 17, 52, 56, 989711, tzinfo=datetime.timezone.utc)),
        ),
    ]
