# Generated by Django 4.2.5 on 2023-11-08 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_notes_date_profilepics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 17, 52, 58, 136335, tzinfo=datetime.timezone.utc)),
        ),
    ]
