# Generated by Django 4.2.5 on 2023-11-08 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_notes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepics',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 18, 56, 51, 685377, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 18, 56, 51, 685377, tzinfo=datetime.timezone.utc)),
        ),
    ]
